# Generated by Django 4.0.4 on 2022-08-31 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_amount_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionamount",
            name="transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculated_amount",
                to="transactions.transaction",
                to_field="uuid",
            ),
        ),
    ]
