# Generated by Django 4.0.4 on 2022-10-06 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0004_alter_transactionamount_transaction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TransactionAmount",
            new_name="TransactionMulticurrency",
        ),
    ]
