# Generated by Django 4.2 on 2023-05-27 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0008_alter_account_workspace"),
        ("budget", "0014_rename_budgetamount_budgetmulticurrency"),
        ("categories", "0008_alter_category_workspace"),
        ("currencies", "0004_alter_currency_workspace"),
        ("transactions", "0006_alter_transactionmulticurrency_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.account",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="budget.budget",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="categories.category",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="currencies.currency",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
    ]
