# Generated by Django 4.2 on 2023-08-02 07:54

from django.db import migrations


def set_default_workspace(apps, schema_editor):
    User = apps.get_model("users", "User")
    Workspace = apps.get_model("workspaces", "Workspace")
    Transaction = apps.get_model("transactions", "Transaction")
    user = User.objects.first()
    workspace = Workspace.objects.filter(owner=user).first()
    if workspace:
        Transaction.objects.filter(workspace=None).update(workspace=workspace)


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_transaction_workspace"),
    ]

    operations = [
        migrations.RunPython(set_default_workspace, migrations.RunPython.noop),
    ]
