# Generated by Django 4.2.20 on 2025-10-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0011_lastviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="source",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
