# Generated by Django 4.0.4 on 2023-01-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_workspace_uuid_alter_workspace_members"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
                to_field="uuid",
            ),
        ),
    ]
