# Generated by Django 4.0.4 on 2023-01-20 14:52

from django.db import migrations


def fix_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    Currency = apps.get_model("currencies", "Currency")

    default_workspace = Workspace.objects.first()
    Currency.objects.update(workspace=default_workspace)


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_currency_workspace"),
    ]

    operations = [migrations.RunPython(fix_workspace, migrations.RunPython.noop)]
