# Generated by Django 4.0.4 on 2023-01-20 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_uuid_alter_workspace_members"),
        ("currencies", "0003_fixing_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
                to_field="uuid",
            ),
        ),
    ]
