# Generated by Django 4.2 on 2023-08-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_alter_workspace_owner"),
        ("currencies", "0004_alter_currency_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name="currency",
            unique_together={("code", "workspace")},
        ),
    ]
