# Generated by Django 4.0.4 on 2022-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='orig_pk',
            field=models.IntegerField(null=True),
        ),
    ]
