# Generated by Django 4.0.4 on 2022-04-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="amount",
            field=models.FloatField(),
        ),
    ]
