# Generated by Django 4.0.4 on 2022-08-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_source_account_title_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="assigned_category",
            new_name="category",
        ),
    ]
