# Generated by Django 4.0.4 on 2023-03-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_created_at_workspace_modified_at'),
        ('accounts', '0006_rename_assigned_category_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='workspaces.workspace', to_field='uuid'),
        ),
    ]
