# Generated by Django 4.0.4 on 2023-03-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_workspace_created_at_workspace_modified_at"),
        ("accounts", "0007_account_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
                to_field="uuid",
            ),
        ),
    ]
