# Generated by Django 4.2.20 on 2026-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_account_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="kind",
            field=models.CharField(
                choices=[("spending", "Spending"), ("savings", "Savings")],
                default="spending",
                max_length=20,
            ),
        ),
    ]
