# Generated by Django 4.0.4 on 2022-05-17 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='base_currency', to='currencies.currency', to_field='uuid'),
        ),
    ]
