# Generated by Django 4.0.4 on 2022-06-21 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0001_initial"),
        ("rates", "0003_auto_20220621_0726"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="base_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="base_currency",
                to="currencies.currency",
                to_field="uuid",
            ),
        ),
    ]
