# Generated by Django 4.0.4 on 2023-01-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0001_initial"),
        ("rates", "0004_alter_rate_base_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="currencies.currency",
                to_field="uuid",
            ),
        ),
    ]
