# Generated by Django 4.0.4 on 2023-01-20 14:53

from django.db import migrations


def fix_workspace(apps, schema_editor):
    Workspace = apps.get_model("workspaces", "Workspace")
    Rate = apps.get_model("rates", "Rate")

    default_workspace = Workspace.objects.first()
    Rate.objects.update(workspace=default_workspace)


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0006_rate_workspace"),
    ]

    operations = [migrations.RunPython(fix_workspace, migrations.RunPython.noop)]
