# Generated by Django 4.2 on 2023-08-04 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0004_alter_workspace_owner"),
        ("currencies", "0005_alter_currency_code_alter_currency_unique_together"),
        ("rates", "0008_alter_rate_workspace"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together={("currency", "rate_date", "workspace")},
        ),
    ]
