# Generated by Django 4.0.4 on 2022-07-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_remove_category_orig_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("INC", "Income"), ("EXP", "Expense")],
                default="EXP",
                max_length=3,
            ),
        ),
    ]
