# Generated by Django 4.0.4 on 2022-08-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_category_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_income",
        ),
    ]
