# Generated by Django 4.2 on 2023-06-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0008_alter_category_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
