# Generated by Django 4.2.11 on 2024-04-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0009_category_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
