# Generated by Django 4.2.11 on 2024-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0011_alter_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
