# Generated by Django 4.2.11 on 2025-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0012_alter_category_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["position"]},
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_name_per_parent"
            ),
        ),
    ]
