# Generated by Django 4.2.11 on 2025-03-18 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0016_update_positions_with_gaps"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="name_parent_null_uniq",
        ),
    ]
