# Generated by Django 4.0.4 on 2023-01-20 10:55

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
