# Generated by Django 4.0.4 on 2023-01-27 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0002_workspace_uuid_alter_workspace_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workspace",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
