# Generated by Django 4.0.4 on 2022-08-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0001_initial"),
        ("budget", "0004_budget_recurrent"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="currencies.currency",
                to_field="uuid",
            ),
        ),
    ]
