# Generated by Django 4.0.4 on 2022-08-09 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0005_budget_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
    ]
