# Generated by Django 4.0.4 on 2022-08-10 12:42

from django.db import migrations


def set_budget_currency(apps, schema_editor):
    budget_items = apps.get_model("budget", "Budget")
    qs = budget_items.objects.filter(currency=None)

    currency_items = apps.get_model("currencies", "Currency")
    if qs.exists():
        base_currency = currency_items.objects.get(is_base=True)

        qs.update(currency=base_currency)


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_budget_user"),
    ]

    operations = [
        migrations.RunPython(set_budget_currency, migrations.RunPython.noop),
    ]
