# Generated by Django 4.0.4 on 2022-08-10 12:51

from django.db import migrations
import os

def set_budget_user(apps, schema_editor):
    budget_items = apps.get_model("budget", "Budget")
    qs = budget_items.objects.filter(user=None)

    admin_user_uuid = os.environ.get("ADMIN_USER_UUID", "")
    user_items = apps.get_model("users", "User")
    admin_user = user_items.objects.get(uuid=admin_user_uuid)

    qs.update(user=admin_user)

class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20220810_1242'),
    ]

    operations = [
        migrations.RunPython(set_budget_user, migrations.RunPython.noop),
    ]
