# Generated by Django 4.0.4 on 2022-08-10 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currencies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0008_auto_20220810_1251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="currencies.currency",
                to_field="uuid",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
    ]
