# Generated by Django 4.0.4 on 2022-08-26 14:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0009_alter_budget_currency_alter_budget_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("amount_map", models.JSONField(default=dict)),
                (
                    "budget",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="budget.budget",
                        to_field="uuid",
                    ),
                ),
            ],
        ),
    ]
