# Generated by Django 4.0.4 on 2022-08-25 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionamount'),
        ('currencies', '0001_initial'),
        ('budget', '0009_alter_budget_currency_alter_budget_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='currencies.currency')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'unique_together': {('transaction', 'currency')},
            },
        ),
    ]
