# Generated by Django 4.0.4 on 2022-09-30 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0011_budget_amount_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetamount",
            name="budget",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="multicurrency",
                to="budget.budget",
                to_field="uuid",
            ),
        ),
    ]
