# Generated by Django 4.0.4 on 2022-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0012_alter_budgetamount_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.FloatField(),
        ),
    ]
