# Generated by Django 4.0.4 on 2022-10-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_budget_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetAmount',
            new_name='BudgetMulticurrency',
        ),
    ]
