# Generated by Django 4.2 on 2023-07-27 06:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0014_rename_budgetamount_budgetmulticurrency"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together={("title", "budget_date", "user")},
        ),
    ]
