# Generated by Django 4.2 on 2023-08-02 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0003_workspace_created_at_workspace_modified_at"),
        ("budget", "0015_alter_budget_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
                to_field="uuid",
            ),
        ),
    ]
