# Generated by Django 4.2 on 2023-08-02 09:12

from django.db import migrations


def set_default_workspace(apps, schema_editor):
    User = apps.get_model("users", "User")
    Workspace = apps.get_model("workspaces", "Workspace")
    Budget = apps.get_model("budget", "Budget")
    user = User.objects.first()
    workspace = Workspace.objects.filter(owner=user).first()
    if workspace:
        Budget.objects.filter(workspace=None).update(workspace=workspace)


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0016_budget_workspace"),
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(set_default_workspace, migrations.RunPython.noop),
    ]
