# Generated by Django 4.2 on 2023-08-02 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_workspace_created_at_workspace_modified_at"),
        ("budget", "0017_auto_20230802_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
                to_field="uuid",
            ),
        ),
    ]
