# Generated by Django 4.2 on 2023-08-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("categories", "0009_category_description"),
        ("budget", "0018_alter_budget_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                to_field="uuid",
            ),
        ),
    ]
