# Generated by Django 4.2.5 on 2023-11-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_alter_budget_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
