# Generated by Django 4.2.20 on 2025-07-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0021_alter_budget_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="recurrent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("occasional", "Occasional"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
