# Generated by Django 4.2.20 on 2026-01-22 11:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0005_alter_currency_code_alter_currency_unique_together"),
        ("workspaces", "0004_alter_workspace_owner"),
        ("categories", "0017_remove_category_name_parent_null_uniq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("budget", "0022_alter_budget_recurrent"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=60)),
                ("amount", models.FloatField()),
                ("start_date", models.DateField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("interval", models.PositiveIntegerField(default=1)),
                ("count", models.PositiveIntegerField(blank=True, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BudgetSeriesException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_skipped", models.BooleanField(default=False)),
                ("override_amount", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="budgetseriesexception",
            name="series",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exceptions",
                to="budget.budgetseries",
            ),
        ),
        migrations.AddField(
            model_name="budgetseries",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="categories.category",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="budgetseries",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="currencies.currency",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="budgetseries",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="budgetseries",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="workspaces.workspace",
                to_field="uuid",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="budget.budgetseries",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("series", "budget_date"), name="unique_series_budget_date"
            ),
        ),
    ]
