# Generated by Django 4.2.20 on 2026-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0024_migrate_recurrent_to_series"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="recurrent",
            field=models.CharField(
                blank=True,
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetseriesexception",
            constraint=models.UniqueConstraint(
                fields=("series", "date"), name="unique_series_exception_date"
            ),
        ),
    ]
