# Generated by Django 4.2.5 on 2024-03-29 13:48

from django.db import migrations
from roles.models import Role


def create_default_roles(apps, schema_editor):
    Role.objects.bulk_create(
        [
            Role(name="owner", is_system=True),
            Role(name="admin", is_system=True),
            Role(name="member", is_system=True),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
